FROM node:alpine

WORKDIR /

ADD . /

RUN npm install --production

ENV PORT=8886

ENV NODE_ENV=develop

ENV SSL_ENV=private

ENV PATH /usr/local/bin:$PATH

EXPOSE ${PORT}

CMD ["npm", "run", "start:develop"]

