module.exports = {
  moduleFileExtensions: ['js', 'json', 'vue'],
  moduleDirectories: ['node_modules', 'modules'],
  testMatch: ['**/*.test.js'],
  moduleNameMapper: {
    '^~/(.*)$': '<rootDir>/src/$1',
    '^@/(.*)$': '<rootDir>/src/$1',
    '^components(.*)$': '<rootDir>/src/components$1',
    '^assets(.*)$': '<rootDir>/src/assets$1',
    '^api(.*)$': '<rootDir>/src/api$1',
    '^stores(.*)$': '<rootDir>/src/store$1',
    '^router(.*)$': '<rootDir>/src/router$1',
    '^languages(.*)$': '<rootDir>/src/languages$1',
    '^models(.*)$': '<rootDir>/src/model$1',
    '^service(.*)$': '<rootDir>/src/service$1',
    '^mixins(.*)$': '<rootDir>/src/mixins$1',
    '^@virnect(.*)$': '<rootDir>/node_modules/@virnect$1',
    '^.+/(.*\\.svg)\\?inline$': '<rootDir>/path/svg/$1',
    '^__utils__(.*)$': '<rootDir>/tests/__utils__$1',
    '^__mocks__(.*)$': '<rootDir>/tests/__mocks__$1',
    '^.+\\.svg$': 'jest-svg-transformer',
  },
  // collectCoverage: true,
  // collectCoverageFrom: ['**/*.{js,vue}'],
  transform: {
    '^.+\\.js$': 'babel-jest',
    '^.+\\.vue$': 'vue-jest',
    '\\.svg$': '<rootDir>/tests/__utils__/fileTransformer.js',
  },
  rootDir: './',
  transformIgnorePatterns: ['<rootDir>/node_modules/(?!@virnect/)'],
  setupFiles: ['<rootDir>/tests/setup.js'],
}
