module.exports = {
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^~/(.*)$': '<rootDir>/$1',
    '^api(.*)$': '<rootDir>/src/api$1',
    '^assets(.*)$': '<rootDir>/src/assets$1',
    '^components(.*)$': '<rootDir>/src/components$1',
    '^languages(.*)$': '<rootDir>/src/languages$1',
    '^layouts(.*)$': '<rootDir>/src/layouts$1',
    '^middleware(.*)$': '<rootDir>/src/middleware$1',
    '^plugins(.*)$': '<rootDir>/src/plugins$1',
    '^mixins(.*)$': '<rootDir>/src/mixins$1',
    '^models(.*)$': '<rootDir>/src/models$1',
    '^pages(.*)$': '<rootDir>/src/pages$1',
    '^services(.*)$': '<rootDir>/src/services$1',
    '^static(.*)$': '<rootDir>/src/static$1',
    '^stores(.*)$': '<rootDir>/src/stores$1',
    '^__utils__(.*)$': '<rootDir>/tests/unit/__utils__$1',
    '^__mocks__(.*)$': '<rootDir>/tests/__mocks__$1',
    '^vue$': 'vue/dist/vue.common.js',
  },
  moduleFileExtensions: ['js', 'vue', 'json'],
  transform: {
    '^.+\\.js$': 'babel-jest',
    '.*\\.(vue)$': 'vue-jest',
    '.+\\.(css|styl|less|sass|scss|png|jpg|ttf|woff|woff2|svg)$':
      'jest-transform-stub',
  },
  collectCoverage: false,
  collectCoverageFrom: [
    '<rootDir>/src/components/**/*.vue',
    '<rootDir>/src/components/*.vue',
    '<rootDir>/src/pages/**/*.vue',
    '<rootDir>/src/pages/*.vue',
  ],
  setupFiles: ['<rootDir>/tests/unit/__utils__/jestSetup.js'],
  testEnvironment: 'jsdom',
  testPathIgnorePatterns: ['/node_modules/'],
}
