export const STATUS = {
  UNLOAD: 'UNLOAD',
  LOAD: 'LOAD',
}

export const WORKSPACE_ROLE = {
  MASTER: 'MASTER',
  MANAGER: 'MANAGER',
  MEMBER: 'MEMBER',
}

export const PLAN_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  EXCEEDED: 'EXCEEDED',
}

export const ROOM_STATUS = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
  OPEN: 'OPEN',
}
