export default {
  currentPage: 0,
  infos: [
    {
      createAt: new Date(),
      duration: 366,
      filename: '2020-09-15 16-57-42_00_협업key.mp4',
      framerate: 20,
      metaData: {},
      recordingId: 'dummyRecordingId',
      resolution: '720p',
      sessionId: 'dummySessionId',
      size: 123,
      userId: 'dummyUserId',
      workspaceId: 'dummyWorkspaceId',
    },
    {
      createAt: new Date(),
      duration: 366,
      filename: '2020-09-15 16-57-42_00_협업key.mp4',
      framerate: 20,
      metaData: {},
      recordingId: 'dummyRecordingId',
      resolution: '720p',
      sessionId: 'dummySessionId',
      size: 123,
      userId: 'dummyUserId',
      workspaceId: 'dummyWorkspaceId',
    },
    {
      createAt: new Date(),
      duration: 366,
      filename: '2020-09-15 16-57-42_00_협업key.mp4',
      framerate: 20,
      metaData: {},
      recordingId: 'dummyRecordingId',
      resolution: '720p',
      sessionId: 'dummySessionId',
      size: 123,
      userId: 'dummyUserId',
      workspaceId: 'dummyWorkspaceId',
    },
    {
      createAt: new Date(),
      duration: 366,
      filename: '2020-09-15 16-57-42_00_협업key.mp4',
      framerate: 20,
      metaData: {},
      recordingId: 'dummyRecordingId',
      resolution: '720p',
      sessionId: 'dummySessionId',
      size: 123,
      userId: 'dummyUserId',
      workspaceId: 'dummyWorkspaceId',
    },
    {
      createAt: new Date(),
      duration: 366,
      filename: '2020-09-15 16-57-42_00_협업key.mp4',
      framerate: 20,
      metaData: {},
      recordingId: 'dummyRecordingId',
      resolution: '720p',
      sessionId: 'dummySessionId',
      size: 9999999,
      userId: 'dummyUserId',
      workspaceId: 'dummyWorkspaceId',
    },
    {
      createAt: new Date(),
      duration: 366,
      filename: '2020-09-15 16-57-42_00_협업key.mp4',
      framerate: 20,
      metaData: {},
      recordingId: 'dummyRecordingId',
      resolution: '720p',
      sessionId: 'dummySessionId',
      size: 123,
      userId: 'dummyUserId',
      workspaceId: 'dummyWorkspaceId',
    },
    {
      createAt: new Date(),
      duration: 366,
      filename: '2020-09-15 16-57-42_00_협업key.mp4',
      framerate: 20,
      metaData: {},
      recordingId: 'dummyRecordingId',
      resolution: '720p',
      sessionId: 'dummySessionId',
      size: 123,
      userId: 'dummyUserId',
      workspaceId: 'dummyWorkspaceId',
    },
    {
      createAt: new Date(),
      duration: 366,
      filename: '2020-09-15 16-57-42_00_협업key.mp4',
      framerate: 20,
      metaData: {},
      recordingId: 'dummyRecordingId',
      resolution: '720p',
      sessionId: 'dummySessionId',
      size: 123,
      userId: 'dummyUserId',
      workspaceId: 'dummyWorkspaceId',
    },
    {
      createAt: new Date(),
      duration: 366,
      filename: '2020-09-15 16-57-42_00_협업key.mp4',
      framerate: 20,
      metaData: {},
      recordingId: 'dummyRecordingId',
      resolution: '720p',
      sessionId: 'dummySessionId',
      size: 123,
      userId: 'dummyUserId',
      workspaceId: 'dummyWorkspaceId',
    },
  ],
  totalPages: 1,
}
