export default {
  fileInfoList: [
    {
      deleted: false,
      expired: false,
      workspaceId: 'string',
      sessionId: 'string',
      name: '더미파일',
      objectName: '2020-08-28_fjxqMrTwIcVmxFIjgfRC',
      contentType: 'image/png',
      size: 12345678,
      createdDate: new Date(),
      expirationDate: new Date(),
    },
    {
      deleted: false,
      expired: true,
      workspaceId: 'string',
      sessionId: 'string',
      name: '만료되었고요',
      objectName: '2020-08-28_fjxqMrTwIcVmxFIjgfRC',
      contentType: 'video/mp4',
      size: 78945612,
      createdDate: new Date(),
      expirationDate: new Date(),
    },
    {
      deleted: false,
      expired: true,
      workspaceId: 'string',
      sessionId: 'string',
      name: '살아았고요',
      objectName: '2020-08-28_fjxqMrTwIcVmxFIjgfRC',
      contentType: 'image/png',
      size: 123456,
      createdDate: new Date(),
      expirationDate: new Date(),
    },
    {
      deleted: false,
      expired: false,
      workspaceId: 'string',
      sessionId: 'string',
      name: '살아았고요',
      objectName: '2020-08-28_fjxqMrTwIcVmxFIjgfRC',
      contentType: 'image/png',
      size: 123456,
      createdDate: new Date(),
      expirationDate: new Date(),
    },
    {
      deleted: false,
      expired: false,
      workspaceId: 'string',
      sessionId: 'string',
      name: '더미 비디오에오',
      objectName: '2020-08-28_fjxqMrTwIcVmxFIjgfRC',
      contentType: 'video/mp4',
      size: 123456,
      createdDate: new Date(),
      expirationDate: new Date(),
    },
  ],
  pageMeta: {
    currentPage: 0,
    currentSize: 2,
    last: false,
    numberOfElements: 2,
    totalElements: 20,
    totalPage: 10,
  },
}
