FROM node:alpine
ENV APP_HOME=/usr/app
ENV PORT=8886
ENV NODE_ENV=develop
ENV SSL_ENV=private

WORKDIR $APP_HOME

ADD . /$APP_HOME

RUN npm install --production

EXPOSE ${PORT}

CMD ["npm", "run", "start:develop"]

