FROM node:alpine
ENV APP_HOME=/usr/app
ENV PORT=8887

WORKDIR $APP_HOME

ADD . $APP_HOME

RUN npm install --production

RUN yarn workspace smic build

EXPOSE $PORT

CMD ["yarn", "workspace", "smic", "deploy"]




