package com.virnect.workspace.global.constant;

import lombok.Getter;

/**
 * Project: PF-Workspace
 * DATE: 2020-07-09
 * AUTHOR: jkleee (Jukyoung Lee)
 * EMAIL: ljk@virnect.com
 * DESCRIPTION:
 */
public enum Mail {
    WORKSPACE_INVITE("MAIL_SUBJECT_WORKSPACE_INVITE", "MAIL_TEMPLATE_WORKSPACE_INVITE"),
    WORKSPACE_INVITE_REJECT("MAIL_SUBJECT_WORKSPACE_INVITE_REJECT", "MAIL_TEMPLATE_WORKSPACE_INVITE_REJECT"),
    WORKSPACE_INVITE_ACCEPT("MAIL_SUBJECT_WORKSPACE_INVITE_ACCEPT", "MAIL_TEMPLATE_WORKSPACE_INVITE_ACCEPT"),
    WORKSPACE_KICKOUT("MAIL_SUBJECT_WORKSPACE_KICKOUT", "MAIL_TEMPLATE_WORKSPACE_KICKOUT"),
    WORKSPACE_INFO_UPDATE("MAIL_SUBJECT_WORKSPACE_INFO_UPDATE", "MAIL_TEMPLATE_WORKSPACE_INFO_UPDATE"),
    WORKSPACE_USER_PERMISSION_UPDATE("MAIL_SUBJECT_WORKSPACE_USER_PERMISSION_UPDATE", "MAIL_TEMPLATE_WORKSPACE_USER_PERMISSION_UPDATE"),
    WORKSPACE_USER_PLAN_UPDATE("MAIL_SUBJECT_WORKSPACE_USER_PLAN_UPDATE", "MAIL_TEMPLATE_WORKSPACE_USER_PLAN_UPDATE"),
    WORKSPACE_OVER_PLAN_FAIL("MAIL_SUBJECT_WORKSPACE_OVER_PLAN_FAIL", "MAIL_TEMPLATE_WORKSPACE_OVER_PLAN_FAIL"),
    WORKSPACE_OVER_MAX_USER_FAIL("MAIL_SUBJECT_WORKSPACE_OVER_MAX_USER_FAIL", "MAIL_TEMPLATE_WORKSPACE_OVER_MAX_USER_FAIL"),
    WORKSPACE_OVER_JOIN_FAIL("MAIL_SUBJECT_WORKSPACE_OVER_JOIN_FAIL", "MAIL_TEMPLATE_WORKSPACE_OVER_JOIN_FAIL"),
    WORKSPACE_INVITE_NON_USER("MAIL_SUBJECT_WORKSPACE_INVITE_NON_USER", "MAIL_TEMPLATE_WORKSPACE_INVITE_NON_USER");

    @Getter
    private String subject;
    @Getter
    private String template;

    Mail(String subject, String template) {
        this.subject = subject;
        this.template = template;
    }
}
