{
 "title": "Media Server",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "id", "query": "select id from rtp" },
   { "name": "env", "query": "select env from rtp" },
   {
    "name": "public_ip",
    "query": "select publicIp from rtp where \"env\" =~ /^$env$/  AND \"time\" >= ${__from}ms AND \"time\" <= ${__to}ms"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Count of Rooms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "room count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "endpoint",
     "query": "SELECT count(distinct(\"pipelineId\")) FROM \"endpoint\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "pipelineId" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "publicIp", "operator": "=~", "value": "/^$public_ip$/" }
     ]
    }
   ]
  },
  {
   "title": "REMB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_mediaType-$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "mediaType" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rtp",
     "query": "SELECT mean(\"remb\") FROM \"rtp\" WHERE (\"mediaType\" = 'VIDEO') AND $timeFilter GROUP BY time($__interval), \"mediaType\", \"type\" fill(none)",
     "select": [
      [
       { "params": [ "remb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "mediaType", "operator": "=", "value": "VIDEO" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "publicIp", "operator": "=~", "value": "/^$public_ip$/" }
     ]
    }
   ]
  },
  {
   "title": "Packets Per Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_mediaType-$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "mediaType" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rtp",
     "query": "SELECT derivative(mean(\"packetsReceived\"), 1s) FROM \"rtp\" WHERE $timeFilter GROUP BY time($__interval), \"mediaType\", \"type\" fill(none)",
     "select": [
      [
       { "params": [ "packetsReceived" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "publicIp", "operator": "=~", "value": "/^$public_ip$/" }
     ]
    },
    {
     "alias": "$tag_mediaType-$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "mediaType" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rtp",
     "query": "SELECT derivative(mean(\"packetsReceived\"), 1s) FROM \"rtp\" WHERE $timeFilter GROUP BY time($__interval), \"mediaType\", \"type\" fill(none)",
     "select": [
      [
       { "params": [ "packetsSent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "publicIp", "operator": "=~", "value": "/^$public_ip$/" }
     ]
    }
   ]
  },
  {
   "title": "Bitrate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_mediaType-$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "mediaType" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rtp",
     "query": "SELECT derivative(mean(\"bytesReceived\"), 1s) *8 FROM \"rtp\" WHERE $timeFilter GROUP BY time($__interval), \"mediaType\", \"type\" fill(none)",
     "select": [
      [
       { "params": [ "bytesReceived" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "publicIp", "operator": "=~", "value": "/^$public_ip$/" }
     ]
    },
    {
     "alias": "$tag_mediaType-$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "mediaType" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rtp",
     "query": "SELECT derivative(mean(\"bytesSent\"), 1s) *-8 FROM \"rtp\" WHERE $timeFilter GROUP BY time($__interval), \"mediaType\", \"type\" fill(none)",
     "select": [
      [
       { "params": [ "bytesSent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*-8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "publicIp", "operator": "=~", "value": "/^$public_ip$/" }
     ]
    }
   ]
  },
  {
   "title": "jitter",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_mediaType-$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "mediaType" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rtp",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "jitter" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "publicIp", "operator": "=~", "value": "/^$public_ip$/" }
     ]
    }
   ]
  },
  {
   "title": "E2E Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "$tag_mediaType",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "mediaType" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "endpoint",
     "query": "SELECT mean(\"videoE2ELatency\") FROM \"endpoint\" WHERE (\"mediaType\" = 'VIDEO') AND $timeFilter GROUP BY time($__interval), \"mediaType\" fill(none)",
     "select": [
      [
       { "params": [ "videoE2ELatency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "mediaType", "operator": "=", "value": "VIDEO" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "publicIp", "operator": "=~", "value": "/^$public_ip$/" }
     ]
    },
    {
     "alias": "$tag_mediaType",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "mediaType" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "endpoint",
     "query": "SELECT mean(\"videoE2ELatency\") FROM \"endpoint\" WHERE (\"mediaType\" = 'VIDEO') AND $timeFilter GROUP BY time($__interval), \"mediaType\" fill(none)",
     "select": [
      [
       { "params": [ "audioE2ELatency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "mediaType", "operator": "=", "value": "AUDIO" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "publicIp", "operator": "=~", "value": "/^$public_ip$/" }
     ]
    }
   ]
  },
  {
   "title": "RTT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_mediaType-$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "mediaType" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rtp",
     "select": [
      [
       { "params": [ "roundTripTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "publicIp", "operator": "=~", "value": "/^$public_ip$/" }
     ]
    }
   ]
  },
  {
   "title": "Packets Lost",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_mediaType-$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "mediaType" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rtp",
     "select": [
      [
       { "params": [ "packetsLost" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "publicIp", "operator": "=~", "value": "/^$public_ip$/" }
     ]
    }
   ]
  },
  {
   "title": "nack count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_mediaType-$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "mediaType" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rtp",
     "select": [
      [
       { "params": [ "nackCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$__interval" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "mediaType", "operator": "=", "value": "VIDEO" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "publicIp", "operator": "=~", "value": "/^$public_ip$/" }
     ]
    }
   ]
  },
  {
   "title": "FIR/PLI/SLI count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "FIR-$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "mediaType" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rtp",
     "select": [
      [
       { "params": [ "firCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "mediaType", "operator": "=", "value": "VIDEO" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "publicIp", "operator": "=~", "value": "/^$public_ip$/" }
     ]
    },
    {
     "alias": "SLI-$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "mediaType" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rtp",
     "select": [
      [
       { "params": [ "sliCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "mediaType", "operator": "=", "value": "VIDEO" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "publicIp", "operator": "=~", "value": "/^$public_ip$/" }
     ]
    },
    {
     "alias": "PLI-$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "mediaType" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rtp",
     "select": [
      [
       { "params": [ "pliCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "mediaType", "operator": "=", "value": "VIDEO" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "publicIp", "operator": "=~", "value": "/^$public_ip$/" }
     ]
    }
   ]
  }
 ]
}