export const CONFIG_CODE = {
  AUDIO_INPUT_DEVICE: 'AUDIO_INPUT_DEVICE',
  AUDIO_OUTPUT_DEVICE: 'AUDIO_OUTPUT_DEVICE',
  VIDEO_DEVICE: 'VIDEO_DEVICE',
  VIDEO_QUALITY: 'VIDEO_QUALITY',
  LANGUAGE: 'LANGUAGE',
  LOCAL_RECORD_LENGTH: 'LOCAL_RECORD_LENGTH',
  RECORD_RESOLUTION: 'RECORD_RESOLUTION',
  NOTI_FLAG_PC: 'NOTI_FLAG_PC',
}
