export const CONFIG_CODE = {
  CURRENT_AUDIO_INPUT_DEVICE: 'CURRENT_AUDIO_INPUT_DEVICE',
  CURRENT_AUDIO_OUTPUT_DEVICE: 'CURRENT_AUDIO_OUTPUT_DEVICE',
  CURRENT_VIDEO_DEVICE: 'CURRENT_VIDEO_DEVICE',
  CURRENT_VIDEO_QUALITY: 'CURRENT_VIDEO_QUALITY',
  CURRENT_LANGUAGE: 'CURRENT_LANGUAGE',
  CURRNET_LOCAL_RECORD_LENGTH: 'CURRNET_LOCAL_RECORD_LENGTH',
  CURRENT_RECORD_RESOLUTION: 'CURRENT_RECORD_RESOLUTION',
}
