pipeline {
    agent any
    environment {
        COMMIT = "${GIT_COMMIT.substring(0,7)}"
        BRANCH = "${BRANCH_NAME.toLowerCase().trim().split("/")[0]}"
        JOB = "${JOB_NAME.split("/")[0].toLowerCase().trim()}"
        REPO_NAME = sh(returnStdout: true, script: 'git config --get remote.origin.url | rev | cut -f 1 -d "/" | rev | sed "s/.git//gi";sed "/^ *$/d"').toLowerCase().trim() 
        SLACK_CHANNEL = '#project-dev-jenkins'
        AUTHOR = sh(returnStdout: true, script : 'git --no-pager show -s --pretty="format: %an"')
        DIR_PATH = "/data/custom/projectdev-base-2.7/minio/onpremise-tar-files"
        TAG_EXIST=sh(script: "git tag | grep ${BRANCH}" , returnStatus: true)
    }
    stages {

        stage('default build'){
            when{
                expression {    
                    return TAG_EXIST != "0" 
                }
            }
            steps {
                script{
                    APP = docker.build("""${JOB_NAME}/${BRANCH_NAME}""", "-f ./docker/Dockerfile .")
                    }
                }
            }
        stage ('save image to harbor') {
                steps {
                    script {
                        docker.withRegistry("https://${HARBOR_REGISTRY}", "harbor") {
                            APP.push("${JOB_NAME}/${BRANCH_NAME}")
                        }
                    }
                }
            }
            
        stage('Deploy'){
            steps {

                scirpt{
                    echo "endndneodnaskdjasdlfkjasdlkf"
                }
               
            }
        }
    }
}
