pipeline {
    agent any
    environment {
        COMMIT = "${GIT_COMMIT.substring(0,7)}"
        BRANCH = "${BRANCH_NAME.toLowerCase().trim().split("/")[0]}"
        JOB = "${JOB_NAME.split("/")[0].toLowerCase().trim()}"
        PORT = sh(returnStdout: true, script: 'cat docker/Dockerfile | egrep EXPOSE | awk \'{print $2}\'').trim()
        REPO_NAME = sh(returnStdout: true, script: 'git config --get remote.origin.url | rev | cut -f 1 -d "/" | rev | sed "s/.git//gi";sed "/^ *$/d"').toLowerCase().trim() 
        SLACK_CHANNEL = '#project-dev-jenkins'
        AUTHOR = sh(returnStdout: true, script : 'git --no-pager show -s --pretty="format: %an"')
        DIR_PATH = "/data/custom/projectdev-base-2.7/minio/onpremise-tar-files"
        TAG_EXIST=sh(script: "git tag | grep ${BRANCH}" , returnStatus: true)
    }
    stages {

        stage('default build'){
            when{
                expression {    
                    return TAG_EXIST != "0" 
                }
            }
            steps {
                script{
                    echo "${JOB}/${BRANCH_NAME}"
                    echo "${JOB}"
                    echo "${BRANCH_NAME}"
                    APP = docker.build("""${JOB}/${BRANCH}""", "-f ./docker/Dockerfile .")
                    }
                }
            }
        stage ('save image to harbor') {
                steps {
                    script {
                        docker.withRegistry("https://${HARBOR_REGISTRY}", "harbor") {
                            APP.push("${env.BUILD_NUMBER}")
                        }
                    }
                }
            }
            
        stage('Deploy'){
            steps {

               script {
                    withCredentials([usernamePassword(credentialsId: 'jtkim_local_pc', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME')]) {
                        def remote = [:]
                        remote.name = "virnect" 
                        remote.host = "${TEST_SERVER}"
                        remote.allowAnyHosts = true 
                        remote.user = USERNAME 
                        remote.password = PASSWORD
                        remote.failOnError = true

                        sshCommand remote: remote, command: """
                            start cmd
                  
                        """
                    }
                }
            }
        }
    }
}
