// account
export const ACCOUNT_SET = 'ACCOUNT_SET'
export const ACCOUNT_CLEAR = 'ACCOUNT_CLEAR'

// oncall
export const CALL_MODE_SET = 'CALL_MODE_SET'
export const CALL_ACTION_SET = 'CALL_ACTION_SET'
export const CALL_STREAM = 'CALL_STREAM'
export const CALL_SPEAKER = 'CALL_SPEAKER'
export const CALL_MIC = 'CALL_MIC'
export const MUTE_ON_OFF = 'MUTE_ON_OFF'

//workspace-settings
export const SETTINGS = {
  SET_AUDIO_INPUT_DEVICE: 'SET_AUDIO_INPUT_DEVICE',
  SET_AUDIO_OUTPUT_DEVICE: 'SET_AUDIO_OUTPUT_DEVICE',
  SET_VIDEO_DEVICE: 'SET_VIDEO_DEVICE',
  SET_VIDEO_QUALITY: 'SET_VIDEO_QUALITY',
  SET_LANGUAGE: 'SET_LANGUAGE',
  SET_LOCAL_RECORD_LENGTH: 'SET_LOCAL_RECORD_LENGTH',
  SET_RECORD_RESOLUTION: 'SET_RECORD_RESOLUTION',
  SET_NOTI_FLAG_PC: 'SET_NOTI_FLAG_PC',
}
