// account
export const ACCOUNT_SET = 'ACCOUNT_SET'
export const ACCOUNT_CLEAR = 'ACCOUNT_CLEAR'
export const WORKSPACE_SET = 'WORKSPACE_SET'
export const INIT_WORKSPACE = 'INIT_WORKSPACE'
export const CHANGE_WORKSPACE = 'CHANGE_WORKSPACE'

// oncall
export const CALL_MODE_SET = 'CALL_MODE_SET'
export const CALL_ACTION_SET = 'CALL_ACTION_SET'
export const CALL_STREAM = 'CALL_STREAM'
export const CALL_SPEAKER = 'CALL_SPEAKER'
export const CALL_MIC = 'CALL_MIC'
export const MUTE_ON_OFF = 'MUTE_ON_OFF'

// tools
export const TOOL_DRAWING_COLOR = 'TOOL_DRAWING_COLOR'
export const TOOL_DRAWING_OPACITY = 'TOOL_DRAWING_OPACITY'
export const TOOL_TEXT_SIZE = 'TOOL_TEXT_SIZE'
export const TOOL_LINE_WIDTH = 'TOOL_LINE_WIDTH'

//workspace-settings
export const SETTINGS = {
  SET_MIC: 'SET_MIC',
  SET_SPEAKER: 'SET_SPEAKER',
  SET_MIC_DEVICE: 'SET_MIC_DEVICE',
  SET_SPEAKER_DEVICE: 'SET_SPEAKER_DEVICE',
  SET_VIDEO_DEVICE: 'SET_VIDEO_DEVICE',
  SET_LANGUAGE: 'SET_LANGUAGE',
  SET_LOCAL_RECORD_LENGTH: 'SET_LOCAL_RECORD_LENGTH',
  SET_RECORD_RESOLUTION: 'SET_RECORD_RESOLUTION',
  SET_LOCAL_RECORD_INTERVAL: 'SET_LOCAL_RECORD_INTERVAL',
}
export const SET_DEVICE = 'SET_DEVICE'

// room
export const ROOM_SET = 'ROOM_SET'
export const ROOM_CLEAR = 'ROOM_CLEAR'

//list search
export const SEARCH_SORT = 'SEARCH_SORT'
export const SEARCH_FILTER = 'SEARCH_FILTER'

// file sharing
export const ADD_HISTORY = 'ADD_HISTORY'
export const REMOVE_HISTORY = 'REMOVE_HISTORY'
export const ADD_FILE = 'ADD_FILE'
export const REMOVE_FILE = 'REMOVE_FILE'
export const ADD_PDF_PAGE = 'ADD_PDF_PAGE'
export const REMOVE_PDF_PAGE = 'REMOVE_PDF_PAGE'
