// account
export const ACCOUNT_SET = 'ACCOUNT_SET'
export const ACCOUNT_CLEAR = 'ACCOUNT_CLEAR'
export const WORKSPACE_SET = 'WORKSPACE_SET'
export const INIT_WORKSPACE = 'INIT_WORKSPACE'
export const CHANGE_WORKSPACE = 'CHANGE_WORKSPACE'
export const CLEAR_WORKSPACE = 'CLEAR_WORKSPACE'
export const SET_COMPANY_INFO = 'SET_COMPANY_INFO'
export const CLEAR_COMPANY_INFO = 'CLEAR_COMPANY_INFO'
export const STATUS_SESSION_ID_SET = 'STATUS_SESSION_ID_SET'

// oncall
export const CALL_RESET = 'CALL_RESET'
export const CALL_MODE_SET = 'CALL_MODE_SET'
export const CALL_ACTION_SET = 'CALL_ACTION_SET'
export const CALL_STREAM = 'CALL_STREAM'
export const CALL_SPEAKER = 'CALL_SPEAKER'
export const CALL_MIC = 'CALL_MIC'
export const MUTE_ON_OFF = 'MUTE_ON_OFF'

// tools
export const TOOL_DRAWING_COLOR = 'TOOL_DRAWING_COLOR'
export const TOOL_DRAWING_OPACITY = 'TOOL_DRAWING_OPACITY'
export const TOOL_TEXT_SIZE = 'TOOL_TEXT_SIZE'
export const TOOL_LINE_WIDTH = 'TOOL_LINE_WIDTH'

//workspace-settings
export const SETTINGS = {
  SET_RECORD: 'SET_RECORD',
  SET_SERVER_RECORD: 'SET_SERVER_RECORD',
  SET_ALLOW: 'SET_ALLOW',
  SET_TRANSLATE_FLAG: 'SET_TRANSLATE_FLAG',
  SET_TRANSLATE_CODE: 'SET_TRANSLATE_CODE',
  SET_TRANSLATE_MULTIPLE: 'SET_TRANSLATE_MULTIPLE',
  SET_STT_SYNC: 'SET_STT_SYNC',
  SET_TTS_ALLOW: 'SET_TTS_ALLOW',
  SET_MIC_DEVICE: 'SET_MIC_DEVICE',
  SET_SPEAKER_DEVICE: 'SET_SPEAKER_DEVICE',
  SET_VIDEO_DEVICE: 'SET_VIDEO_DEVICE',
  SET_LOCAL_RECORD_TARGET: 'SET_LOCAL_RECORD_TARGET',
  SET_LOCAL_RECORD_STATUS: 'SET_LOCAL_RECORD_STATUS',
  SET_SERVER_RECORD_STATUS: 'SET_SERVER_RECORD_STATUS',
  SET_SCREEN_STRICT: 'SET_SCREEN_STRICT',
}
export const ALLOW_RESET = 'ALLOW_RESET'
export const TOGGLE_CHAT = 'TOGGLE_CHAT'
export const SET_DEVICE = 'SET_DEVICE'

// room
export const ROOM_SET = 'ROOM_SET'
export const ADD_ROOM_MEMBER = 'ADD_ROOM_MEMBER'
export const REMOVE_ROOM_MEMBER = 'REMOVE_ROOM_MEMBER'
export const ROOM_CLEAR = 'ROOM_CLEAR'

// file sharing
export const FILE_RESET = 'FILE_RESET'
export const SHOW_IMAGE = 'SHOW_IMAGE'
export const SHOW_AR_IMAGE = 'SHOW_AR_IMAGE'
export const UPDATE_SHARE = 'UPDATE_SHARE'
export const ADD_HISTORY = 'ADD_HISTORY'
export const UPDATE_HISTORY = 'UPDATE_HISTORY'
export const REMOVE_HISTORY = 'REMOVE_HISTORY'
export const ADD_FILE = 'ADD_FILE'
export const REMOVE_FILE = 'REMOVE_FILE'
export const ADD_PDF_PAGE = 'ADD_PDF_PAGE'
export const REMOVE_PDF_PAGE = 'REMOVE_PDF_PAGE'
export const SET_CAPTURE = 'SET_CAPTURE'

// alarm
export const ADD_ALARM = 'ADD_ALARM'
export const REMOVE_ALARM = 'REMOVE_ALARM'
export const UPDATE_ALARM = 'UPDATE_ALARM'

//spot fullscreen mode
export const SET_SPOT_FULLSCREEN = 'SET_SPOT_FULLSCREEN'

export const SET_IS_SPOT_STAND = 'SET_IS_SPOT_STAND'
